export enum ProductCategory {
  FRUITS_AND_VEGETABLES = 'FRUITS_AND_VEGETABLES',
  DAIRY_AND_EGGS = 'DAIRY_AND_EGGS',
  BAKERY = 'BAKERY',
  MEAT_AND_SEAFOOD = 'MEAT_AND_SEAFOOD',
  BEVERAGES = 'BEVERAGES',
  SNACKS_AND_CONFECTIONERY = 'SNACKS_AND_CONFECTIONERY',
  PERSONAL_CARE = 'PERSONAL_CARE',
  HOUSEHOLD_CLEANING = 'HOUSEHOLD_CLEANING',
  FROZEN_FOODS = 'FROZEN_FOODS',
  STAPLES_AND_GRAINS = 'STAPLES_AND_GRAINS'
}